Implement #1259 - Improve build script adding support for Linux and Mac
Badgerati/Pode pull request #1261
Opened 2024-03-25 17:23 UTC by mdaneri

### Description of the Change
Add support for Linux, and macOS builds
Add the Assembly version to the C# build
Add support for .Net 8.0 build
Add Clean task
Add Install-Module and Remove-Module tasks
Add Documentation
Update to Pester 5.5 call
 

### Additional Context
 Pester 5.5  migration  #1260 is required to make the new build works

2024-03-29 14:28 UTC, Badgerati requested changes

2024-03-29 14:28 UTC, Badgerati commented on pode.build.ps1
> +        $configuration.Output.Verbosity = 'Detailed'
This overrides the verbosity value passed by the user, and set at lie 338 above.

2024-03-29 23:18 UTC, Badgerati commented on pode.build.ps1
> +function Invoke-PodeBuildDotnetBuild($target,$Version) {
The calls to `Invoke-PodeBuildDotnetBuild` still reference the `-Version` parameter :)

2024-03-29 23:20 UTC, mdaneri commented on pode.build.ps1
> +function Invoke-PodeBuildDotnetBuild($target,$Version) {
damn I tested on the wrong branch

2024-03-30 10:24 UTC, Badgerati requested changes

2024-03-30 10:24 UTC, Badgerati commented on pode.build.ps1
> +    Compress-Archive -Path './pkg' -DestinationPath "$path/$Version-Binaries.zip"
`./pkg` on `Compress-Archive` will need to be `./pkg/*`, otherwise the zip created will contain the pkg folder as well.

2024-03-30 10:24 UTC, Badgerati commented on packers/choco/pode_template.nuspec
In the `<files>` section, the following line to move /tools:
```xml
<file src="tools\**" target="tools" />
```
will need to be replaced the following, otherwise the templated ps1 will be included in the final choco package:
```xml
<file src="tools\ChocolateyInstall.ps1" target="tools" />
<file src="tools\ChocolateyUninstall.ps1" target="tools" />
```

2024-03-30 10:24 UTC, Badgerati commented on .gitignore
>  pkg/
Like how `pkg/` is in the gitignore, `deliverable/` should be as well :)

2024-03-31 19:40 UTC, Badgerati approved these changes
LGTM, is there any more to be added or good for merging?

2024-03-31 19:42 UTC, mdaneri commented
Done

2024-03-31 19:55 UTC, merged