Updated examples
Badgerati/Pode pull request #1333
Opened 2024-06-13 18:15 UTC by mdaneri

### Changes:
- Listener moved to localhost and port 8081 when possible,
- Import-Module generate an exception if fails
- cleanup 
- tested

2024-07-09 19:18 UTC, Badgerati requested changes

2024-07-09 19:18 UTC, Badgerati commented on examples/web-pages-docker.ps1
> +    Add-PodeEndpoint -Address * -Port 8081 -Protocol Http
There's a `docker-compose.yml` and a `Dockerfile` in the examples folder which will need ports updating to 8081 as well :)

2024-07-10 16:15 UTC, mdaneri commented
I have not done yet with this. 
I plan to make a change in Pode.build.ps1 to automatically create an md document with any example with a brief description + a test to check if any example has the correct header for the build to create the page

2024-07-11 16:33 UTC, mdaneri commented
.LINK is available on the summary page
.EXAMPLE do you think is needed?

2024-09-02 11:34 UTC, Badgerati requested changes

2024-09-02 11:34 UTC, Badgerati commented on pode.build.ps1
> +Task IndexSamples {
This task could be simplified to the following; which also fixes a few bugs with the original as well:
* Fixes bug with GitHub URLs missing subfolders
* Fixes issue with no extra space between multiple lines being concatenated
* Changed the page title to be just "Sample Scripts"
* The "Index" isn't needed in mkdocs, as mkdocs will make it automatically on the right

```powershell
Task IndexSamples {
    $examplesPath = './examples'
    if (!(Test-Path -PathType Container -Path $examplesPath)) {
        return
    }

    # List of directories to exclude
    $sampleMarkDownPath = './docs/Getting-Started/Samples.md'
    $excludeDirs = @('scripts', 'views', 'static', 'public', 'assets', 'timers', 'modules',
        'Authentication', 'certs', 'logs', 'relative', 'routes')

    # Convert exlusion list into single regex pattern for directory matching
    $dirSeparator = [IO.Path]::DirectorySeparatorChar
    $excludeDirs = "\$($dirSeparator)($($excludeDirs -join '|'))\$($dirSeparator)"

    # build the page content
    Get-ChildItem -Path $examplesPath -Filter *.ps1 -Recurse -File -Force |
        Where-Object {
            $_.FullName -inotmatch $excludeDirs
        } |
        Sort-Object -Property FullName |
        ForEach-Object {
            Write-Verbose "Processing Sample: $($_.FullName)"

            # get the script help
            $help = Get-Help -Name $_.FullName -ErrorAction Stop

            # add help content
            $urlFileName = ($_.FullName -isplit 'examples')[1].Trim('\/') -replace '[\\/]', '/'
            $markdownContent += "## [$($_.BaseName)](https://github.com/Badgerati/Pode/blob/develop/examples/$($urlFileName))`n`n"
            $markdownContent += "**Synopsis**`n`n$($help.Synopsis)`n`n"
            $markdownContent += "**Description**`n`n$($help.Description.Text)`n`n"
        }

    Write-Output "Write Markdown document for the sample files to $($sampleMarkDownPath)"
    Set-Content -Path $sampleMarkDownPath -Value "# Sample Scripts`n`n$($markdownContent)" -Force
}
```

2024-09-02 11:34 UTC, Badgerati commented on tests/unit/_.Tests.ps1
> +BeforeDiscovery {
Similar to the new Task, the BeforeDiscovery here can be simplified:

```powershell
BeforeDiscovery {
    $path = $PSCommandPath
    $examplesPath = (Split-Path -Parent -Path $path) -ireplace '[\\/]tests[\\/]unit', '/examples/'

    # List of directories to exclude
    $excludeDirs = @('scripts', 'views', 'static', 'public', 'assets', 'timers', 'modules',
        'Authentication', 'certs', 'logs', 'relative', 'routes')

    # Convert exlusion list into single regex pattern for directory matching
    $dirSeparator = [IO.Path]::DirectorySeparatorChar
    $excludeDirs = "\$($dirSeparator)($($excludeDirs -join '|'))\$($dirSeparator)"

    # get the example scripts
    $ps1Files = @(Get-ChildItem -Path $examplesPath -Filter *.ps1 -Recurse -File -Force |
        Where-Object {
            $_.FullName -inotmatch $excludeDirs
        }).FullName
}
```

2024-09-02 11:34 UTC, Badgerati commented on examples/Web-Auth-Digest.ps1
Name needs changing to be `Web-AuthDigest`, to match the format of the others

2024-09-02 11:34 UTC, Badgerati commented on examples/TcpServer-Auth.ps1
Id change the name to be `Tcp-ServerAuth`, to match the format of the "Web" ones

2024-09-02 11:34 UTC, Badgerati commented on examples/TcpServer-Http.ps1
Id change the name to be `Tcp-ServerHttp`, to match the format of the "Web" ones

2024-09-02 11:34 UTC, Badgerati commented on examples/TcpServer-MultiEndpoint.ps1
Id change the name to be `Tcp-ServerMultiEndpoint`, to match the format of the "Web" ones

2024-09-02 11:34 UTC, Badgerati commented on examples/Rest-Api.ps1
I'd change this to be `Web-RestApi.ps1`

2024-09-02 11:34 UTC, Badgerati commented on examples/Nunit-RestApi.ps1
I'd change this to be `Web-NunitRestApi.ps1`

2024-09-02 11:34 UTC, Badgerati commented on examples/Web-Pages.ps1
There are two references to this file in `./examples/package.json`, which will need updating to be `./Web-Pages.ps1` with the new casing.

2024-09-02 11:34 UTC, Badgerati commented on examples/Web-PagesDocker.ps1
There's a reference to this file in `./examples/Dockerfile` which will need updating to be `./Web-PagesDocker.ps1`. The exposed port will also need updating to `8081` as well.

2024-09-02 15:13 UTC, mdaneri commented on examples/sse.ps1
This coming from the last merge. I don't see it on my Windows. Let me delete it from the repository

2024-09-02 15:50 UTC, mdaneri commented on examples/Web-Pages.ps1
I missed it 
thanks

2024-09-02 17:49 UTC, Badgerati approved these changes

2024-09-02 17:51 UTC, merged