Rfc9512
Badgerati/Pode pull request #1352
Opened 2024-07-06 23:31 UTC by mdaneri

### Description of the Change
A clear and concise description of what has been changed.

### Related Issue
A link/reference to the GitHub issue.

### Examples
If relevant, include any examples of using what you have changed.

### Additional Context
Add any other context or screenshots about the pull request request here.

2024-07-07 21:22 UTC, Badgerati requested changes
Besides the 2 minor change comments, everything else LGTM

2024-07-07 21:22 UTC, Badgerati commented on src/Public/Responses.ps1
> +Because JSON content has not yet an official content type. one custom can be specified here (Default: 'application/yaml' )
Should be "Because YAML content" etc.

2024-07-07 21:22 UTC, Badgerati commented on src/Public/Responses.ps1
> +Because JSON content has not yet an official content type. one custom can be specified here (Default: 'application/xml' )
Should be "Because XML content" etc.

2024-07-07 21:25 UTC, mdaneri commented on src/Public/Responses.ps1
> +Because JSON content has not yet an official content type. one custom can be specified here (Default: 'application/xml' )
opps copy and paste virus hit again :D

2024-07-08 17:49 UTC, Badgerati approved these changes

2024-07-08 17:49 UTC, merged